version: '3.9'
services:
  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    # environment:
    #   ENV_VAR: potato
    env_file:
      - .env

  api1: &api
    build:
      context: .
    volumes:
      - .:/app # add our local code to dockerfile
    # Allows multi web container, instead of pid already exists: https://ieftimov.com/posts/docker-compose-stray-pids-rails-beyond/#stray-pid-files
    tmpfs:
      - /app/tmp
    env_file:
      - .env
    depends_on:
      - db # add all dependant container
  api2:
    <<: *api

  load_balancer:
    image: nginx
    container_name: load_balancer
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 9999:9999
    depends_on:
      - api1
      - api2

volumes:
  pg-data: # named volume
